name = "quiz-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
CORS_ORIGIN = "http://localhost:5173"

[[d1_databases]]
binding = "QUIZ_DB"
database_name = "quiz-db"
database_id = "0a558ed7-baa9-4991-9886-a37540f680bd"

[[kv_namespaces]]
binding = "QUIZ_KV"
id = "6073df4a8bf84a7585941507daf917f4"
preview_id = "REPLACE_WITH_PREVIEW_KV_ID"

[env.production]
vars = { CORS_ORIGIN = "https://tanong.com" }
